language: node_js
dist: xenial
os: linux
node_js:
  - 14
install:
  - bash scripts/travis_install.sh
script:
  - bash scripts/travis_test.sh
before_deploy:
  - bash scripts/travis_build.sh
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &repo_info
    repo: nbdaaron/capen.dev
  bucket: capen-dev-code
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: capen-dev-code
  key: latest.zip
  bundle_type: zip
  application: capen
  deployment_group: capen
  region: us-east-1
  on: *repo_info
