language: node_js
dist: xenial
os: linux
node_js:
  - 14
script:
  - bash run_tests.sh
before_deploy:
  - rm -rf frontend/node_modules
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  cleanup: false
  on: &repo_info
    repo: nbdaaron/capen.dev
  bucket: capen-dev-code
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: capen-dev-code
  key: latest.zip
  bundle_type: zip
  application: capen
  deployment_group: capen
  region: us-east-1
  on: *repo_info
